### PR TITLE
Also spelling mistake

### PR DESCRIPTION
**Pull request by arafalov**
But I am less sure if it is just spelling fix or something else required as well.

### CODE REVIEW

**Comment by pbartusch** [comment]
hey @arafalov , thanks for the correction 👍

**Comment by arafalov** [comment]
Glad it was helpful. Just a note that I accidentally created two pull request for this (one against each file). So, the UI one is still open.

**Comment by pbartusch** [comment]
true - I just closed #17

**Comment by epugh** [comment]
I see this fix, however I think the right place to fix this in `application.conf`!  Will submit another PR for that ;-)   Hi @arafalov nice to see your PR!

**Pull request merged**
